"""add allow photo to offer

Revision ID: dd493556db17
Revises: 7975dd572d0f
Create Date: 2024-03-09 10:45:47.319483

"""
from typing import Sequence
from typing import Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'dd493556db17'
down_revision: Union[str, None] = '7975dd572d0f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('offers', sa.Column('allow_photo', sa.Boolean(), server_default=sa.text('false'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('offers', 'allow_photo')
    # ### end Alembic commands ###
