"""add booking status

Revision ID: 11f03fb0e6fb
Revises: bc61f904acbb
Create Date: 2024-02-25 10:47:33.245907

"""
from typing import Sequence
from typing import Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '11f03fb0e6fb'
down_revision: Union[str, None] = 'bc61f904acbb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    booking_status = sa.Enum('ACTIVE', 'CANCELLED', 'COMPLETED', name='bookingstatus')
    booking_status.create(op.get_bind())
    op.add_column('bookings', sa.Column('status', booking_status, nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bookings', 'status')
    booking_status = sa.Enum('ACTIVE', 'CANCELLED', 'COMPLETED', name='bookingstatus')
    booking_status.drop(op.get_bind())
    # ### end Alembic commands ###
