"""update business and working hours

Revision ID: 21849848b74f
Revises: 11f03fb0e6fb
Create Date: 2024-03-03 12:07:35.242202

"""
from typing import Sequence
from typing import Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '21849848b74f'
down_revision: Union[str, None] = '11f03fb0e6fb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(sa.text("ALTER TYPE bookingstatus ADD VALUE 'NEW';"))
    op.execute(sa.text("ALTER TYPE bookingstatus ADD VALUE 'CONFIRMED';"))

    op.create_table(
        'booking_attachments_association',
        sa.Column('booking_id', sa.Integer(), nullable=False),
        sa.Column('attachment_id', sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ['attachment_id'],
            ['attachments.id'],
        ),
        sa.ForeignKeyConstraint(
            ['booking_id'],
            ['bookings.id'],
        ),
        sa.PrimaryKeyConstraint('booking_id', 'attachment_id'),
    )
    op.add_column('bookings', sa.Column('comment', sa.String(length=1000), nullable=True))
    op.add_column('businesses', sa.Column('slug', sa.String(length=200), nullable=False))
    op.create_index(op.f('ix_businesses_slug'), 'businesses', ['slug'], unique=True)
    op.add_column('working_hours', sa.Column('date_from', sa.DateTime(timezone=True), nullable=False))
    op.add_column('working_hours', sa.Column('date_to', sa.DateTime(timezone=True), nullable=False))
    op.drop_index('ix_working_hours_date', table_name='working_hours')
    op.create_index(op.f('ix_working_hours_date_from'), 'working_hours', ['date_from'], unique=False)
    op.create_index(op.f('ix_working_hours_date_to'), 'working_hours', ['date_to'], unique=False)
    op.drop_column('working_hours', 'date')
    op.drop_column('working_hours', 'closing_time')
    op.drop_column('working_hours', 'opening_time')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('working_hours', sa.Column('opening_time', postgresql.TIME(), autoincrement=False, nullable=False))
    op.add_column('working_hours', sa.Column('closing_time', postgresql.TIME(), autoincrement=False, nullable=False))
    op.add_column('working_hours', sa.Column('date', sa.DATE(), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_working_hours_date_to'), table_name='working_hours')
    op.drop_index(op.f('ix_working_hours_date_from'), table_name='working_hours')
    op.create_index('ix_working_hours_date', 'working_hours', ['date'], unique=False)
    op.drop_column('working_hours', 'date_to')
    op.drop_column('working_hours', 'date_from')
    op.drop_index(op.f('ix_businesses_slug'), table_name='businesses')
    op.drop_column('businesses', 'slug')
    op.drop_column('bookings', 'comment')
    op.drop_table('booking_attachments_association')
    # ### end Alembic commands ###
