exclude: fixtures/|.gitlab-ci.yml
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
        args: [ --markdown-linebreak-ext=md ]
        files: ^beauty_models/.*\.py$
      - id: end-of-file-fixer
        exclude: static|README.md|release_notes
        files: ^beauty_models/.*\.py$
      - id: check-docstring-first
        files: ^beauty_models/.*\.py$
      - id: debug-statements
        files: ^beauty_models/.*\.py$
      - id: name-tests-test
        exclude: factories.py
        files: ^beauty_models/(.+/)?tests/.+\.py$
      - id: double-quote-string-fixer
        files: ^beauty_models/.*\.py$
  - repo: https://github.com/psf/black
    rev: 23.7.0
    hooks:
      - id: black
        args: [ --line-length=120, -S ]
        files: ^beauty_models/.*\.py$
  - repo: https://github.com/pycqa/flake8
    rev: 6.0.0
    hooks:
      - id: flake8
        additional_dependencies:
          - flake8-typing-imports
          - flake8-comprehensions
          - flake8-eradicate
          - flake8-spellcheck
          - dlint
          - darglint
          - mccabe
          - pep8-naming
          - flake8-isort
        args:
          - "--max-line-length=120"
          - "--classmethod-decorators=classmethod"
          - "--whitelist=whitelist.txt"
          - "--config=.flake8"
        files: ^beauty_models/.*\.py$
  - repo: local
    hooks:
      - id: mypy
        name: Mypy check
        entry: sh -c 'mypy --config-file=.mypy.ini beauty_models || exit 1'
        language: system
        pass_filenames: false
        files: ^beauty_models/.*\.py$
      - id: bandit-security-check
        name: Bandit security check
        entry: bandit
        args: [ -q, -x, test ]
        language: system
        files: beauty_models/apps/
      - id: safety-production-dependencies-check
        name: Safety production dependencies check
        entry: bash -c 'poetry export -f requirements.txt | safety check --full-report --stdin -i 51159'
        language: system
        files: poetry.lock
      - id: safety-development-dependencies-check
        name: Safety development dependencies check
        entry: bash -c 'poetry export -f requirements.txt --with dev | safety check --full-report --stdin -i 51159'
        language: system
        files: poetry.lock